apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
spec:
  replicas: 15  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website-container
        # image: vimal13/apache-webserver-php
        image: m95kandan/website
        ports:
        - containerPort: 80
