- name: Push Docker Images to Docker Hub
  hosts: docker_host
  become: yes

  vars:
    docker_image_tags:
      - "{{ build_number_tag }}"
      - "latest"

  tasks:
    - name: Log in to Docker Hub
      command: "docker login -u {{ dockerhub_username }} -p {{ dockerhub_password }}"
      become: yes

    - name: Push Docker images to Docker Hub
      command: "docker push {{ dockerhub_repository }}:{{ item }}"
      become: yes
      loop: "{{ docker_image_tags }}"
